import 'dart:io';
import 'package:excel/excel.dart';
import 'package:flutter/services.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:share_plus/share_plus.dart';
import 'package:khataplus/features/dashboard/data/models/transaction_model.dart';
import 'package:intl/intl.dart';

class ExportService {
  static Future<void> exportLedgerToPdf({
    required String title,
    required List<TransactionModel> transactions,
    required String businessName,
  }) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (context) => [
          pw.Header(
            level: 0,
            child: pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text(businessName, style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
                pw.Text(title, style: const pw.TextStyle(fontSize: 18)),
              ],
            ),
          ),
          pw.SizedBox(height: 20),
          pw.TableHelper.fromTextArray(
            headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
            headers: ['Date', 'Description', 'Type', 'Amount'],
            data: transactions.map((tx) => [
              DateFormat('dd MMM yyyy').format(tx.date),
              tx.description ?? '-',
              tx.type == TransactionType.credit ? 'Cash In' : 'Cash Out',
              'Rs. ${tx.amount.toStringAsFixed(2)}',
            ]).toList(),
          ),
          pw.SizedBox(height: 20),
          pw.Align(
            alignment: pw.Alignment.centerRight,
            child: pw.Text(
              'Generated by DigiKhata Pro',
              style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey),
            ),
          ),
        ],
      ),
    );

    await Printing.layoutPdf(onLayout: (PdfPageFormat format) async => pdf.save());
  }

  static Future<void> exportLedgerToExcel({
    required List<TransactionModel> transactions,
    required String fileName,
  }) async {
    var excel = Excel.createExcel();
    Sheet sheetObject = excel['Ledger'];

    sheetObject.appendRow([
      TextCellValue('Date'),
      TextCellValue('Description'),
      TextCellValue('Type'),
      TextCellValue('Amount'),
      TextCellValue('Notes'),
    ]);

    for (var tx in transactions) {
      sheetObject.appendRow([
        TextCellValue(DateFormat('dd-MM-yyyy').format(tx.date)),
        TextCellValue(tx.description ?? ''),
        TextCellValue(tx.type == TransactionType.credit ? 'Credit' : 'Debit'),
        DoubleCellValue(tx.amount),
        TextCellValue(tx.notes ?? ''),
      ]);
    }

    final directory = await getTemporaryDirectory();
    final path = "${directory.path}/$fileName.xlsx";
    final file = File(path);
    
    final bytes = excel.save();
    if (bytes != null) {
      await file.writeAsBytes(bytes);
      await Share.shareXFiles([XFile(path)], text: 'Business Ledger Export');
    }
  }
}
