import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:khataplus/core/theme/app_colors.dart';
import 'package:khataplus/core/services/supabase_service.dart';
import 'package:khataplus/features/auth/presentation/login/widgets/custom_text_field.dart';
import 'package:khataplus/features/auth/presentation/login/widgets/primary_button.dart';
import 'package:khataplus/features/auth/presentation/login/widgets/curved_header.dart';
import 'package:khataplus/features/business/data/models/business_model.dart';
import '../providers/business_provider.dart';

class CreateBusinessScreen extends ConsumerStatefulWidget {
  const CreateBusinessScreen({super.key});

  @override
  ConsumerState<CreateBusinessScreen> createState() => _CreateBusinessScreenState();
}

class _CreateBusinessScreenState extends ConsumerState<CreateBusinessScreen> {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  final _phoneController = TextEditingController();
  final _addressController = TextEditingController();
  String _selectedType = 'Retail Shop';
  String _selectedCurrency = 'PKR';
  bool _isLoading = false;

  @override
  void dispose() {
    _nameController.dispose();
    _phoneController.dispose();
    _addressController.dispose();
    super.dispose();
  }

  void _handleSave() async {
    if (_formKey.currentState!.validate()) {
      setState(() => _isLoading = true);
      
      final userId = ref.read(supabaseServiceProvider).currentUser?.id;
      if (userId != null) {
        final newBusiness = BusinessModel(
          id: '', // Will be generated by DB
          ownerId: userId,
          name: _nameController.text.trim(),
          type: _selectedType,
          phone: _phoneController.text.trim(),
          address: _addressController.text.trim(),
          currency: _selectedCurrency,
          createdAt: DateTime.now(),
        );

        await ref.read(businessListProvider.notifier).createBusiness(newBusiness);
        
        if (mounted) {
          setState(() => _isLoading = false);
          Navigator.pop(context);
        }
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.background,
      body: SingleChildScrollView(
        child: Form(
          key: _formKey,
          child: Column(
            children: [
              CurvedHeader(
                height: MediaQuery.of(context).size.height * 0.25,
                child: SafeArea(
                  child: Column(
                    children: [
                      const SizedBox(height: 10),
                      Row(
                        children: [
                          IconButton(
                            icon: const Icon(Icons.arrow_back, color: Colors.white),
                            onPressed: () => Navigator.pop(context),
                          ),
                          Expanded(
                            child: Center(
                              child: Text(
                                'Add New Business',
                                style: GoogleFonts.poppins(
                                  fontSize: 22,
                                  fontWeight: FontWeight.bold,
                                  color: Colors.white,
                                ),
                              ),
                            ),
                          ),
                          const SizedBox(width: 48),
                        ],
                      ),
                    ],
                  ),
                ),
              ),
              const SizedBox(height: 24),
              Padding(
                padding: const EdgeInsets.symmetric(horizontal: 24),
                child: Column(
                  children: [
                    CustomTextField(
                      hintText: 'Business Name',
                      prefixIcon: Icons.business_center_outlined,
                      controller: _nameController,
                      validator: (val) => val == null || val.isEmpty ? 'Field required' : null,
                    ),
                    const SizedBox(height: 20),
                    _buildDropdownField(
                      'Business Type',
                      Icons.category_outlined,
                      ['Retail Shop', 'Wholesale', 'Service Provider', 'Others'],
                      _selectedType,
                      (val) => setState(() => _selectedType = val!),
                    ),
                    const SizedBox(height: 20),
                    CustomTextField(
                      hintText: 'Phone Number',
                      prefixIcon: Icons.phone_outlined,
                      keyboardType: TextInputType.phone,
                      controller: _phoneController,
                    ),
                    const SizedBox(height: 20),
                    CustomTextField(
                      hintText: 'Address',
                      prefixIcon: Icons.location_on_outlined,
                      controller: _addressController,
                    ),
                    const SizedBox(height: 20),
                    _buildDropdownField(
                      'Currency',
                      Icons.monetization_on_outlined,
                      ['PKR', 'INR', 'USD', 'EUR'],
                      _selectedCurrency,
                      (val) => setState(() => _selectedCurrency = val!),
                    ),
                    const SizedBox(height: 40),
                    _isLoading
                        ? const CircularProgressIndicator()
                        : PrimaryButton(
                            text: 'Save Business',
                            onPressed: _handleSave,
                          ),
                    const SizedBox(height: 40),
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildDropdownField(String hint, IconData icon, List<String> items, String value, ValueChanged<String?> onChanged) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 20),
      height: 64,
      decoration: BoxDecoration(
        color: AppColors.inputBackground,
        borderRadius: BorderRadius.circular(18),
        border: Border.all(color: AppColors.border),
      ),
      child: Row(
        children: [
          Icon(icon, color: AppColors.primaryBlue),
          const SizedBox(width: 12),
          Expanded(
            child: DropdownButtonHideUnderline(
              child: DropdownButton<String>(
                value: value,
                isExpanded: true,
                items: items.map((String value) {
                  return DropdownMenuItem<String>(
                    value: value,
                    child: Text(value, style: GoogleFonts.poppins(fontSize: 15, fontWeight: FontWeight.w500)),
                  );
                }).toList(),
                onChanged: onChanged,
              ),
            ),
          ),
        ],
      ),
    );
  }
}
