import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:khataplus/core/theme/app_colors.dart';
import 'package:khataplus/core/services/supabase_service.dart';
import 'package:khataplus/features/auth/presentation/login/widgets/custom_text_field.dart';
import 'package:khataplus/features/auth/presentation/login/widgets/primary_button.dart';
import 'package:khataplus/features/business/presentation/providers/business_provider.dart';
import 'package:khataplus/features/customer/presentation/providers/customer_provider.dart';
import '../../data/models/transaction_model.dart';
import '../providers/dashboard_provider.dart';

import 'package:image_picker/image_picker.dart';
import 'package:intl/intl.dart';
import 'package:khataplus/features/supplier/presentation/providers/supplier_provider.dart';
import 'package:easy_localization/easy_localization.dart';
import 'package:khataplus/features/dashboard/presentation/providers/transaction_provider.dart';

enum TransactionParty { customer, supplier }

class AddTransactionScreen extends ConsumerStatefulWidget {
  final TransactionType type;
  const AddTransactionScreen({super.key, required this.type});

  @override
  ConsumerState<AddTransactionScreen> createState() => _AddTransactionScreenState();
}

class _AddTransactionScreenState extends ConsumerState<AddTransactionScreen> {
  final _formKey = GlobalKey<FormState>();
  final _amountController = TextEditingController();
  final _descriptionController = TextEditingController();
  final _notesController = TextEditingController();
  
  TransactionParty _selectedParty = TransactionParty.customer;
  String? _selectedId;
  DateTime _selectedDate = DateTime.now();
  XFile? _selectedImage;
  bool _isLoading = false;

  @override
  void dispose() {
    _amountController.dispose();
    _descriptionController.dispose();
    _notesController.dispose();
    super.dispose();
  }

  Future<void> _pickDate() async {
    final picked = await showDatePicker(
      context: context,
      initialDate: _selectedDate,
      firstDate: DateTime(2000),
      lastDate: DateTime.now(),
    );
    if (picked != null) setState(() => _selectedDate = picked);
  }

  Future<void> _pickImage() async {
    final picker = ImagePicker();
    final image = await picker.pickImage(source: ImageSource.gallery, imageQuality: 50);
    if (image != null) setState(() => _selectedImage = image);
  }

  void _handleSave() async {
    if (_formKey.currentState!.validate() && _selectedId != null) {
      setState(() => _isLoading = true);
      
      try {
        final businessId = ref.read(selectedBusinessIdProvider);
        if (businessId == null) return;

        final supabase = ref.read(supabaseServiceProvider).client;
        
        String? imageUrl;
        if (_selectedImage != null) {
          try {
            final bytes = await _selectedImage!.readAsBytes();
            final fileName = 'tx_${DateTime.now().millisecondsSinceEpoch}.jpg';
            final path = 'transactions/$businessId/$fileName';
            await supabase.storage.from('transactions').uploadBinary(path, bytes);
            imageUrl = supabase.storage.from('transactions').getPublicUrl(path);
          } catch (_) {
            // If offline, we proceed without image upload or handle it in sync
            // For now, simpler to just skip image if upload fails
          }
        }

        final tx = TransactionModel(
          id: '', // Generated by repo
          businessId: businessId,
          amount: double.parse(_amountController.text),
          description: _descriptionController.text,
          notes: _notesController.text,
          type: widget.type,
          date: _selectedDate,
          imageUrl: imageUrl,
          customerId: _selectedParty == TransactionParty.customer ? _selectedId : null,
          supplierId: _selectedParty == TransactionParty.supplier ? _selectedId : null,
        );
        
        await ref.read(transactionActionProvider).addTransaction(tx);

        ref.refresh(dashboardStatsProvider);
        ref.read(customersProvider.notifier).loadCustomers();
        ref.read(suppliersProvider.notifier).loadSuppliers();

        if (mounted) {
          Navigator.pop(context);
        }
      } catch (e) {
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(content: Text('Error: $e'), backgroundColor: AppColors.error),
          );
        }
      } finally {
        if (mounted) setState(() => _isLoading = false);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final customers = ref.watch(customersProvider).value ?? [];
    final suppliers = ref.watch(suppliersProvider).value ?? [];
    final isCredit = widget.type == TransactionType.credit;
    final isDarkMode = Theme.of(context).brightness == Brightness.dark;

    return Scaffold(
      backgroundColor: Theme.of(context).scaffoldBackgroundColor,
      appBar: AppBar(
        title: Text(
          isCredit ? 'Cash In (Credit)' : 'Cash Out (Debit)',
          style: GoogleFonts.poppins(
            fontWeight: FontWeight.bold,
            color: isDarkMode ? Colors.white : AppColors.textPrimary,
          ),
        ),
        backgroundColor: Colors.transparent,
        elevation: 0,
        iconTheme: IconThemeData(color: isDarkMode ? Colors.white : AppColors.textPrimary),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(24),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // Party Selection (Customer/Supplier)
              Center(
                child: SegmentedButton<TransactionParty>(
                  segments: const [
                    ButtonSegment(value: TransactionParty.customer, label: Text('Customer'), icon: Icon(Icons.person)),
                    ButtonSegment(value: TransactionParty.supplier, label: Text('Supplier'), icon: Icon(Icons.business)),
                  ],
                  selected: {_selectedParty},
                  onSelectionChanged: (set) {
                    setState(() {
                      _selectedParty = set.first;
                      _selectedId = null;
                    });
                  },
                  style: SegmentedButton.styleFrom(
                    backgroundColor: isDarkMode ? AppColors.logoNavyBottom : Colors.white,
                    selectedBackgroundColor: AppColors.primaryBlue,
                    selectedForegroundColor: Colors.white,
                  ),
                ),
              ),
              const SizedBox(height: 24),
              
              Text(
                _selectedParty == TransactionParty.customer ? 'select_customer'.tr() : 'select_supplier'.tr(),
                style: GoogleFonts.inter(
                  fontWeight: FontWeight.w600, 
                  color: isDarkMode ? Colors.white70 : AppColors.textSecondary,
                ),
              ),
              const SizedBox(height: 12),
              DropdownButtonFormField<String>(
                value: _selectedId,
                dropdownColor: isDarkMode ? AppColors.logoNavyBottom : Colors.white,
                style: TextStyle(color: isDarkMode ? Colors.white : AppColors.textPrimary),
                decoration: InputDecoration(
                  filled: true,
                  fillColor: isDarkMode ? AppColors.logoNavyBottom : AppColors.inputBackground,
                  border: OutlineInputBorder(borderRadius: BorderRadius.circular(16), borderSide: BorderSide.none),
                  contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
                ),
                items: (_selectedParty == TransactionParty.customer 
                        ? customers.map((c) => DropdownMenuItem(value: c.id, child: Text(c.name))).toList()
                        : suppliers.map((s) => DropdownMenuItem(value: s.id, child: Text(s.name))).toList()),
                onChanged: (val) => setState(() => _selectedId = val),
                validator: (val) => val == null ? 'Please select a ${_selectedParty.name}' : null,
              ),
              const SizedBox(height: 24),

              // Date Selection
              InkWell(
                onTap: _pickDate,
                borderRadius: BorderRadius.circular(16),
                child: Container(
                  padding: const EdgeInsets.all(16),
                  decoration: BoxDecoration(
                    color: isDarkMode ? AppColors.logoNavyBottom : AppColors.inputBackground,
                    borderRadius: BorderRadius.circular(16),
                  ),
                  child: Row(
                    children: [
                      const Icon(Icons.calendar_today, color: AppColors.primaryBlue),
                      const SizedBox(width: 12),
                      Text(
                        DateFormat('dd MMMM yyyy').format(_selectedDate),
                        style: GoogleFonts.inter(
                          fontWeight: FontWeight.w500,
                          color: isDarkMode ? Colors.white : AppColors.textPrimary,
                        ),
                      ),
                      const Spacer(),
                      const Text('Change', style: TextStyle(color: AppColors.primaryBlue, fontSize: 12)),
                    ],
                  ),
                ),
              ),
              const SizedBox(height: 24),

              CustomTextField(
                hintText: 'Amount',
                prefixIcon: Icons.attach_money,
                controller: _amountController,
                keyboardType: TextInputType.number,
                validator: (val) => val == null || val.isEmpty ? 'Required' : null,
              ),
              const SizedBox(height: 20),
              CustomTextField(
                hintText: 'Description',
                prefixIcon: Icons.description_outlined,
                controller: _descriptionController,
              ),
              const SizedBox(height: 20),
              CustomTextField(
                hintText: 'Notes',
                prefixIcon: Icons.notes,
                controller: _notesController,
              ),
              const SizedBox(height: 24),

              // Image Attachment
              InkWell(
                onTap: _pickImage,
                borderRadius: BorderRadius.circular(16),
                child: Container(
                  height: 120,
                  width: double.infinity,
                  decoration: BoxDecoration(
                    color: isDarkMode ? AppColors.logoNavyBottom : AppColors.inputBackground,
                    borderRadius: BorderRadius.circular(16),
                    border: Border.all(color: isDarkMode ? Colors.white10 : AppColors.border),
                  ),
                  child: _selectedImage == null
                      ? Column(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            const Icon(Icons.add_a_photo_outlined, color: AppColors.primaryBlue),
                            const SizedBox(height: 8),
                            Text(
                              'Attach Receipt Image', 
                              style: GoogleFonts.inter(color: isDarkMode ? Colors.white70 : AppColors.textSecondary),
                            ),
                          ],
                        )
                      : ClipRRect(
                          borderRadius: BorderRadius.circular(16),
                          child: Image.file(
                            File(_selectedImage!.path),
                            fit: BoxFit.cover,
                          ),
                        ),
                ),
              ),

              const SizedBox(height: 40),
              _isLoading
                  ? const Center(child: CircularProgressIndicator())
                  : PrimaryButton(
                      text: 'save_entry'.tr(),
                      onPressed: _handleSave,
                    ),
            ],
          ),
        ),
      ),
    );
  }
}
